//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class uso
    {
        public int id { get; set; }
        public string Cuenta { get; set; }
        public string accion { get; set; }
        public int monto { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
